

const Product = [
    {
        products:"Almendras",
        id:"1",
        category:"Fruto Seco",
        price:500,
        gram:100,
        description:"Almendras sin cascaras Origen Argentina, Provincia de Buenos Aires",
    },
    {
        products:"Castañas de Caju",
        id:"2",
        category:"Fruto Seco",
        price:470,
        gram:100,
        description:"Castañas de Caju sin cascaras Origen Argentina, Provincia de Mendoza",
    },
    {
        products:"Nueces",
        id:"3",
        category:"Fruto Seco",
        price:450,
        gram:100,
        description:"Nueces sin cascaras Origen Argentina, Provincia de Mendoza",
    },
    {
        products:"Mani con Cascaras",
        id:"4",
        category:"Fruto Seco",
        price:200,
        gram:100,
        description:"Mani con Cascaras Origen Argentina, Provincia de Mendoza",
    },
    {
        products:"Mani Pelado",
        id:"5",
        category:"Fruto Seco",
        price:250,
        gram:100,
        description:"Mani Pelado cascaras Origen Argentina, Provincia de Mendoza",
    },
    {
        products:"Pistacho",
        id:"6",
        category:"Fruto Seco",
        price:650,
        gram:100,
        description:"Pistacho con cascaras Origen Argentina, Provincia de San Juan",
    },
    {
        products:"Avellana",
        id:"7",
        category:"Fruto Seco",
        price:600,
        gram:100,
        description:"Avellana sin cascaras Origen Argentina, Provincia de Rio Negro",
    },
    {
        products:"Granola",
        id:"8",
        category:"Cereal Mix",
        price:450,
        gram:100,
        description:"  Esta hecho con frutos secos (almendras y nueces), avena, mezclado con miel y horneado hasta quedar crujiente. Tambien cuenta con semillas (girasol, zapallo, lino, sésamo) y frutas deshidratadas (pasas y plátano) Origen Argentina, Provincia de Buenos aires",
    },
    {
        products:"Avena",
        id:"9",
        category:"Cereal",
        price:300,
        gram:100,
        description:"  Avena suelta Origen Argentina, Provincia de Buenos aires",
    },
    {
        products:"Mix Frutos Secos",
        id:"10",
        category:"Frutos Secos Mix",
        price:550,
        gram:100,
        description:"Mix Frutos Secos sin cascaras Origen Argentina, Provincia de Mendoza",
    },
    {
        products:"Mix de Semillas",
        id:"11",
        category:"Mix de Semillas",
        price:300,
        gram:100,
        description:"Mix de Semillas sin cascaras Origen Argentina, Provincia de Buenos Aires",
    },
    {
        products:"Mix Cervecero",
        id:"12",
        category:"Mix Cervecero",
        price:400,
        gram:100,
        description:"Mix Cervecero sin cascaras frito con sal agregado Origen Argentina, Provincia de Buenos Aires",
    },
    {
        products:"Mix Tropical",
        id:"13",
        category:"Mix Tropical",
        price:450,
        gram:100,
        description:"Mix Tropical sin cascaras con frutas desecadas y frutos secos Origen Argentina, Provincia de Buenos Aires",
    },
    {
        products:"Frutas Desecadas",
        id:"14",
        category:"Frutas Desecadas",
        price:500,
        gram:100,
        description:"Frutas Desecadas kiwi, banana, cereza, anana, frutillas Origen Argentina, Provincia de Buenos Aires",
    },{
        products:"Pasas de Uvas",
        id:"15",
        category:"Pasas de Uvas",
        price:250,
        gram:100,
        description:"Pasas de Uvas Violetas Origen Argentina, Provincia de Buenos Aires",
    },
    {
        products:"Pasas de Uvas Rubias",
        id:"16",
        category:"Pasas de Uvas Rubias",
        price:250,
        gram:100,
        description:"Pasas de Uvas Rubas Origen Argentina, Provincia de Buenos Aires",
    },
  ]